default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: trine_development

test:
  <<: *default
  database: trine_test

production:
  <<: *default
  database: trine_production
